version: "3"
services:
  app:
    build: .
    container_name: simple-task-java
    environment:
      - spring.datasource.url=jdbc:postgresql://db:5432/test
      - spring.datasource.username=postgres
      - spring.datasource.password=mysecretpassword
      - spring.profiles.active=postgres
    ports:
      - 8080:8081
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=test
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
#  db:
#    image: mysql
#    container_name: db
#    environment:
#      MYSQL_DATABASE: test
#      MYSQL_USER: mysql
#      MYSQL_PASSWORD: mysecretpassword
#      MYSQL_ROOT_PASSWORD: root
#    ports:
#      - 3306:3306
#    volumes:
#      - db_data:/var/lib/mysql/data
volumes:
  db_data: